Update PlaguedMurderers.cs
I have updated the code to not throw errors "Error while compiling: PlaguedMurderers.cs(290,46): error CS0246: The type or namespace name `HTNPlayer' could not be found. Are you missing an assembly reference?" when loading.